# Generated by Django 2.1 on 2019-01-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
    ]
